# Generated by Django 5.1.2 on 2024-11-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('imagenUrlMa', models.URLField(blank=True, null=True)),
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('imagenUrlDis', models.URLField(blank=True, null=True)),
                ('idDispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='appMediaDeusto.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('camara', models.CharField(max_length=100)),
                ('capacidadBateriaMAH', models.IntegerField()),
                ('procesador', models.CharField(max_length=1000)),
                ('imagenUrlMo', models.URLField(blank=True, null=True)),
                ('idModelo', models.AutoField(primary_key=True, serialize=False)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='appMediaDeusto.dispositivo')),
            ],
        ),
    ]
