# Generated by Django 5.1.2 on 2024-11-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagenUrlMa', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagenUrlDis', models.URLField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='appMediaDeusto.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('procesador', models.CharField(blank=True, max_length=1000)),
                ('ram', models.CharField(blank=True, max_length=1000)),
                ('grafica', models.CharField(blank=True, max_length=1000)),
                ('capacidadBateriaMAH', models.IntegerField()),
                ('camara', models.CharField(blank=True, max_length=100)),
                ('audio', models.CharField(blank=True, max_length=100)),
                ('proteccionIP', models.CharField(blank=True, max_length=1000)),
                ('imagenUrlMo', models.URLField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='appMediaDeusto.dispositivo')),
            ],
        ),
    ]
