# Generated by Django 5.1.2 on 2024-11-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMediaDeusto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='audio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='grafica',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='modelo',
            name='proteccionIP',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='modelo',
            name='ram',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='camara',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='procesador',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
