# Generated by Django 5.1.2 on 2024-11-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMediaDeusto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='precio',
            field=models.FloatField(default=0.0, max_length=100),
        ),
    ]
