# Generated by Django 5.1.2 on 2024-12-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMediaDeusto', '0002_modelo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
    ]
